import { useEffect, useMemo, useRef } from 'react';
import './GlowCursor.css';

export default function GlowCursor({ children, color = '#67E8F9', secondaryColor = '#106ae4', trailLength = 20, trailWidth = 8, trailTaper = .8, followSpeed = .5, glowIntensity = 1.9, glowSpread = 1.2, brightness = 1.25, opacity = 1, pulseSpeed = 1.1, idleFade = false, idleTimeout = 700, fadeDuration = 900, blendMode = 'screen' }) {
  const rootRef = useRef(null), pointRefs = useRef([]);
  const points = useMemo(() => Array.from({ length: trailLength }, () => ({ x: -100, y: -100 })), [trailLength]);
  useEffect(() => { let target = { x: -100, y: -100 }, frame, idleTimer; const root = rootRef.current; const move = event => { target = { x: event.clientX, y: event.clientY }; root.classList.remove('glow-cursor--idle'); if (idleFade) { clearTimeout(idleTimer); idleTimer = setTimeout(() => root.classList.add('glow-cursor--idle'), idleTimeout); } }; const draw = () => { points.forEach((point, index) => { const destination = index ? points[index - 1] : target, speed = Math.min(1, Math.max(.02, followSpeed * (index ? .72 : 1))); point.x += (destination.x - point.x) * speed; point.y += (destination.y - point.y) * speed; const node = pointRefs.current[index]; if (node) node.style.transform = `translate3d(${point.x}px,${point.y}px,0) translate(-50%,-50%)`; }); frame = requestAnimationFrame(draw); }; addEventListener('pointermove', move, { passive: true }); if (idleFade) idleTimer = setTimeout(() => root.classList.add('glow-cursor--idle'), idleTimeout); frame = requestAnimationFrame(draw); return () => { removeEventListener('pointermove', move); cancelAnimationFrame(frame); clearTimeout(idleTimer); }; }, [followSpeed, idleFade, idleTimeout, points]);
  return <div ref={rootRef} className="glow-cursor" style={{ '--glow-color': color, '--glow-secondary': secondaryColor, '--glow-intensity': glowIntensity, '--glow-spread': glowSpread, '--glow-brightness': brightness, '--pulse-speed': `${pulseSpeed}s`, '--fade-duration': `${fadeDuration}ms`, mixBlendMode: blendMode }}>{children}<div className="glow-cursor__trail" aria-hidden="true">{points.map((_, index) => { const progress = index / Math.max(1, trailLength - 1), size = trailWidth * (1 - progress * trailTaper); return <i key={index} ref={node => { pointRefs.current[index] = node; }} style={{ width: size, height: size, opacity: opacity * (1 - progress * .78) }} />; })}</div></div>;
}
