import { useEffect, useRef } from 'react';
import { Renderer, Program, Mesh, Triangle } from 'ogl';
import './Lightfall.css';

const MAX_COLORS=8;
const hexToRGB=hex=>{const c=hex.replace('#','').padEnd(6,'0');return [parseInt(c.slice(0,2),16)/255,parseInt(c.slice(2,4),16)/255,parseInt(c.slice(4,6),16)/255]};
const prepColors=input=>{const base=(input?.length?input:['#A6C8FF','#5227FF','#FF9FFC']).slice(0,MAX_COLORS),arr=[];for(let i=0;i<MAX_COLORS;i++)arr.push(hexToRGB(base[Math.min(i,base.length-1)]));return {arr,count:base.length,avg:arr.slice(0,base.length).reduce((a,c)=>a.map((v,i)=>v+c[i]),[0,0,0]).map(v=>v/base.length)}};
const vertex=`attribute vec2 position;attribute vec2 uv;varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const fragment=`precision highp float;uniform vec3 iResolution;uniform vec2 iMouse;uniform float iTime;uniform vec3 uColor0,uColor1,uColor2,uColor3,uColor4,uColor5,uColor6,uColor7,uBgColor,uMouseColor;uniform int uColorCount,uStreakCount;uniform float uSpeed,uStreakWidth,uStreakLength,uGlow,uDensity,uTwinkle,uZoom,uBgGlow,uOpacity,uMouseEnabled,uMouseStrength,uMouseRadius;varying vec2 vUv;vec3 palette(float h){int i=int(floor(clamp(h,0.,.999999)*float(max(uColorCount,1))));if(i==0)return uColor0;if(i==1)return uColor1;if(i==2)return uColor2;if(i==3)return uColor3;if(i==4)return uColor4;if(i==5)return uColor5;if(i==6)return uColor6;return uColor7;}vec3 tanhv(vec3 x){vec3 e=exp(-2.*x);return(1.-e)/(1.+e);}vec2 sceneC(vec2 f,vec2 r){vec2 P=(f+f-r)/r.x;float z=0.,d=1e3;vec4 O;for(int k=0;k<39;k++){if(d<=1e-4)break;O=z*normalize(vec4(P,uZoom,0.))-vec4(0.,4.,1.,0.)/4.5;d=1.-sqrt(length(O*O));z+=d;}return vec2(O.x,atan(O.z,O.y));}void main(){vec2 r=iResolution.xy,C=vUv*r,uv0=(C+C-r)/r.x;float T=.1*iTime*uSpeed+9.,rings=max(1.,floor(6.2831853*max(uDensity,.05)+.5));vec2 Y=vec2(.005,6.2831853/rings),c0=sceneC(C,r),dx=sceneC(C+vec2(1.,0.),r)-c0,dy=sceneC(C+vec2(0.,1.),r)-c0;dx.y-=6.2831853*floor(dx.y/6.2831853+.5);dy.y-=6.2831853*floor(dy.y/6.2831853+.5);vec2 fw=abs(dx)+abs(dy);C=c0;vec2 P=vec2(2.,1.)*uv0-(r/r.x)*vec2(0.,1.);vec4 O=vec4(uBgColor*90.*uBgGlow/(1e3*dot(P,P)+6.),0.);float mg=0.;if(uMouseEnabled>.5){vec2 mn=(iMouse+iMouse-r)/r.x;float md=length(uv0-mn);mg=exp(-md*md/max(uMouseRadius*uMouseRadius,1e-4))*uMouseStrength;O.rgb+=uMouseColor*mg*.25;}float zr=5e-4*uStreakWidth;vec2 rr=vec2(max(length(fw),1e-5));float tail=19./max(uStreakLength,.05);for(int m=0;m<16;m++){if(m>=uStreakCount)break;float jf=float(m)+1.,ic=fract(sin(dot(vec2(jf,floor(C.x/Y.x+.5)),vec2(7.,11.))*73.);vec2 pp=C-(T+T*ic)*vec2(0.,1.);pp-=floor(pp/Y+.5)*Y;float h=fract(8663.*ic),weight=mix(1.5,1.+sin(T+7.*h+4.),uTwinkle)*(1.+mg*2.);vec2 inner=vec2(length(max(pp,vec2(-1.,0.))),length(pp)-zr)-zr,sm=vec2(1.)-smoothstep(-rr,rr,inner);O.rgb+=dot(sm,vec2(exp(tail*pp.y),3.))*palette(h)*weight;C.x+=Y.x/8.;}vec3 col=sqrt(tanhv(max(O.rgb*uGlow-vec3(.04,.08,.02),0.)));gl_FragColor=vec4(col,uOpacity);}`;

export default function Lightfall({className='',dpr,paused=false,colors=['#A6C8FF','#5227FF','#FF9FFC'],backgroundColor='#0A29FF',speed=.5,streakCount=2,streakWidth=1,streakLength=1,glow=1,density=.6,twinkle=1,zoom=3,backgroundGlow=.5,opacity=1,mouseInteraction=true,mouseStrength=.5,mouseRadius=1,mouseDampening=.15}){const containerRef=useRef(null);useEffect(()=>{const container=containerRef.current;if(!container)return;const renderer=new Renderer({dpr:(dpr??devicePixelRatio)||1,alpha:true,antialias:true}),gl=renderer.gl,canvas=gl.canvas;Object.assign(canvas.style,{width:'100%',height:'100%',display:'block'});container.appendChild(canvas);const {arr,count,avg}=prepColors(colors),uniforms={iResolution:{value:[1,1,1]},iMouse:{value:[0,0]},iTime:{value:0},uColor0:{value:arr[0]},uColor1:{value:arr[1]},uColor2:{value:arr[2]},uColor3:{value:arr[3]},uColor4:{value:arr[4]},uColor5:{value:arr[5]},uColor6:{value:arr[6]},uColor7:{value:arr[7]},uColorCount:{value:count},uBgColor:{value:hexToRGB(backgroundColor)},uMouseColor:{value:avg},uSpeed:{value:speed},uStreakCount:{value:Math.max(1,Math.min(16,Math.round(streakCount)))},uStreakWidth:{value:streakWidth},uStreakLength:{value:streakLength},uGlow:{value:glow},uDensity:{value:density},uTwinkle:{value:twinkle},uZoom:{value:zoom},uBgGlow:{value:backgroundGlow},uOpacity:{value:opacity},uMouseEnabled:{value:mouseInteraction?1:0},uMouseStrength:{value:mouseStrength},uMouseRadius:{value:mouseRadius}},program=new Program(gl,{vertex,fragment,uniforms}),mesh=new Mesh(gl,{geometry:new Triangle(gl),program});const resize=()=>{const rect=container.getBoundingClientRect();renderer.setSize(rect.width,rect.height);uniforms.iResolution.value=[gl.drawingBufferWidth,gl.drawingBufferHeight,1]};resize();const ro=new ResizeObserver(resize);ro.observe(container);const target=[0,0];const move=e=>{const rect=canvas.getBoundingClientRect(),scale=renderer.dpr||1;target[0]=(e.clientX-rect.left)*scale;target[1]=(rect.height-(e.clientY-rect.top))*scale;if(mouseDampening<=0)uniforms.iMouse.value=[...target]};if(mouseInteraction)canvas.addEventListener('pointermove',move);let raf,last=0;const loop=t=>{raf=requestAnimationFrame(loop);uniforms.iTime.value=t*.001;if(mouseDampening>0){const factor=1-Math.exp(-((t-last||0)/1000)/Math.max(mouseDampening,1e-4));last=t;uniforms.iMouse.value[0]+=(target[0]-uniforms.iMouse.value[0])*factor;uniforms.iMouse.value[1]+=(target[1]-uniforms.iMouse.value[1])*factor}if(!paused)renderer.render({scene:mesh})};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);ro.disconnect();canvas.removeEventListener('pointermove',move);canvas.remove();gl.getExtension('WEBGL_lose_context')?.loseContext()}},[dpr,paused,colors,backgroundColor,speed,streakCount,streakWidth,streakLength,glow,density,twinkle,zoom,backgroundGlow,opacity,mouseInteraction,mouseStrength,mouseRadius,mouseDampening]);return <div ref={containerRef} className={`lightfall-container ${className}`.trim()}/>}
