import { useEffect, useRef } from 'react';
import { Renderer, Program, Mesh, Triangle } from 'ogl';
import './WebThreads.css';

const hexToRgb = hex => {
  const parts = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return parts ? [parseInt(parts[1], 16) / 255, parseInt(parts[2], 16) / 255, parseInt(parts[3], 16) / 255] : [1, 1, 1];
};
const FAN_MODE = { center: 0, left: 1, right: 2 };
const vertex = `#version 300 es
in vec2 position; void main() { gl_Position = vec4(position, 0.0, 1.0); }`;
const fragment = `#version 300 es
precision highp float;
uniform vec2 iResolution; uniform float iTime,uSpeed,uThreadCount,uFrequency,uSpread,uTaper,uPosition,uFanMode,uGlow,uFalloff,uThickness,uBrightness,uOpacity,uMirror,uShimmer,uGrain,uGrainIntensity,uMouseStrength,uEnableMouse,uMouseActive; uniform vec3 uColor1,uColor2,uColor3; uniform vec2 uMouse; out vec4 fragColor;
#define TAU 6.28318530718
#define MAX_THREADS 10
float glow(float x,float str,float dist){return dist/pow(max(x,1e-4),str);}
void main(){vec2 uv=gl_FragCoord.xy/iResolution.xy;float n=max(uThreadCount,1.);float pinchX=uFanMode<.5?.5:(uFanMode<1.5?0.:1.);if(uEnableMouse>.5)pinchX=mix(pinchX,uMouse.x,clamp(uMouseStrength,0.,1.)*uMouseActive);float spreadDx=uSpread*abs(uv.x-pinchX),baseT=iTime*uSpeed,tauOverN=TAU/n,mirror=uMirror>.5?sign(pinchX-uv.x):1.,invThickness=1./max(uThickness,.01),xFreq=uv.x*uFrequency,yOff=uv.y-uPosition,ciScale=n>1.?1./(n-1.):0.;vec3 col=vec3(0.);float gsum=0.;for(int idx=0;idx<MAX_THREADS;idx++){float i=float(idx);if(i>=n)break;float amplitude=spreadDx*(1.+i*uTaper);float shimmer=uShimmer>.5?sin(iTime*1.7+i*1.3)*.35:0.;float phase=(baseT+i*tauOverN)*mirror+shimmer;float sdf=abs(yOff+sin(xFreq+phase)*amplitude)*invThickness;float g=glow(sdf,uFalloff,uGlow);col+=g*mix(uColor1,uColor2,i*ciScale);gsum+=g;}col=mix(col,uColor3*gsum,smoothstep(.5,2.2,gsum)*.5);float bright=uBrightness;if(uEnableMouse>.5){vec2 md=uv-uMouse;bright+=clamp(uMouseStrength,0.,1.)*uMouseActive*exp(-dot(md,md)*6.)*.6;}col*=bright;float alpha=clamp(gsum,0.,1.)*uOpacity;vec3 outRgb=col*alpha;if(uGrain>.5){float gv=(fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233))+iTime)*43758.5453)-.5)*uGrainIntensity;outRgb=clamp(outRgb+gv,0.,1.);alpha=clamp(alpha+gv,0.,1.);}fragColor=vec4(outRgb,alpha);}`;

export default function WebThreads({ color1='#0085ff',color2='#2183c6',color3='#4ab0ed',speed=.2,threadCount=6,frequency=5,spread=.18,taper=1,position=.5,fanMode='center',glow=.02,falloff=.6,thickness=1.1,brightness=.6,opacity=1,mirror=true,shimmer=false,grain=true,grainIntensity=.05,mouseInteraction=true,mouseStrength=.3,className='' }) {
  const containerRef=useRef(null), mouseRef=useRef({ enabled:mouseInteraction,strength:mouseStrength });
  useEffect(()=>{const container=containerRef.current;if(!container)return;const renderer=new Renderer({webgl:2,alpha:true,premultipliedAlpha:true,antialias:false,dpr:Math.min(devicePixelRatio||1,2)}),gl=renderer.gl,canvas=gl.canvas;gl.clearColor(0,0,0,0);Object.assign(canvas.style,{width:'100%',height:'100%',display:'block'});container.appendChild(canvas);const program=new Program(gl,{vertex,fragment,uniforms:{iTime:{value:0},iResolution:{value:new Float32Array([1,1])},uSpeed:{value:speed},uThreadCount:{value:threadCount},uFrequency:{value:frequency},uSpread:{value:spread},uTaper:{value:taper},uPosition:{value:position},uFanMode:{value:FAN_MODE[fanMode]??0},uGlow:{value:glow},uFalloff:{value:falloff},uThickness:{value:thickness},uBrightness:{value:brightness},uOpacity:{value:opacity},uMirror:{value:mirror?1:0},uShimmer:{value:shimmer?1:0},uGrain:{value:grain?1:0},uGrainIntensity:{value:grainIntensity},uColor1:{value:new Float32Array(hexToRgb(color1))},uColor2:{value:new Float32Array(hexToRgb(color2))},uColor3:{value:new Float32Array(hexToRgb(color3))},uMouse:{value:new Float32Array([.5,.5])},uMouseStrength:{value:mouseStrength},uEnableMouse:{value:mouseInteraction?1:0},uMouseActive:{value:0}}}),mesh=new Mesh(gl,{geometry:new Triangle(gl),program});const resize=()=>{const r=container.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height));program.uniforms.iResolution.value.set([gl.drawingBufferWidth,gl.drawingBufferHeight])};const ro=new ResizeObserver(resize);ro.observe(container);resize();const current=[.5,.5],target=[.5,.5];let active=0,targetActive=0,raf=0;const move=e=>{const r=canvas.getBoundingClientRect();target[0]=(e.clientX-r.left)/r.width;target[1]=1-(e.clientY-r.top)/r.height;targetActive=1};const leave=()=>targetActive=0;canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseenter',move);canvas.addEventListener('mouseleave',leave);const start=performance.now();const loop=t=>{program.uniforms.iTime.value=(t-start)/1000;current[0]+=(target[0]-current[0])*.05;current[1]+=(target[1]-current[1])*.05;active+=(targetActive-active)*.05;program.uniforms.uMouse.value.set(current);program.uniforms.uMouseActive.value=active;renderer.render({scene:mesh});raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);ro.disconnect();canvas.removeEventListener('mousemove',move);canvas.removeEventListener('mouseenter',move);canvas.removeEventListener('mouseleave',leave);canvas.remove();gl.getExtension('WEBGL_lose_context')?.loseContext()}},[]);
  useEffect(()=>{const u=containerRef.current?.querySelector('canvas');mouseRef.current={enabled:mouseInteraction,strength:mouseStrength};if(!u)return;},[mouseInteraction,mouseStrength]);
  return <div ref={containerRef} className={`web-threads-container ${className}`.trim()}/>;
}
